# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed3742660e6c7759bd65010c706ffb4e771c1dd1d75959cac745450585c063c7ba8012817ea0c328789c968cd3a38ea8740b4d317735d4a9bf964e70e090d833

test:
  secret_key_base: 210063858624410fdedd351e4d1ab906e29a077bf0d20f0f40bf0e88ec95c5957187bf709e5dd681ea0eb828c672548e77c22879c55d134afc24a49b46cfc041

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
